### PR TITLE
Updated to RxRelay2

### PR DESCRIPTION
**Pull request by marcinkunert**
Updated to RxRelay2, as it is already available for some time: https://github.com/JakeWharton/RxRelay/pull/20

### CODE REVIEW

**Comment by ravikumar-n** [comment]
@kaushikgopal Isn't this already [merged into rxjava_2 branch ](https://github.com/kaushikgopal/RxJava-Android-Samples/pull/88)?

**Comment by kaushikgopal** [comment]
@ravikumar-n is right. he was kind enough to add this already. i'm guessing @marcinkunert you were working off an older master?

closing this for now, as the latest master should have the updated RxRelay

**Comment by ravikumar-n** [comment]
@kaushikgopal  But I don't find the master has the updated code. Had you overwritten it or what?

**Comment by kaushikgopal** [comment]
ah shoot. you're right. so the PR was merged onto the feature branch after the feature branch was already merged onto master. i'll fix this shortly.

**Pull request closed without merging**
